apiVersion: v1
kind: Service
metadata:
  name: {{ include "featherbit-operator.webhookServiceName" . }}
  labels:
    {{- include "featherbit-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "featherbit-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featherbit-operator.fullname" . }}-metrics
  labels:
    {{- include "featherbit-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "featherbit-operator.selectorLabels" . | nindent 4 }}
